# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PCD\Prak_Pcd\p1\A7\A7.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 1021)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(240, 480, 75, 23))
        self.loadButton.setObjectName("loadButton")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(60, 50, 450, 420))
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.hasilLabel = QtWidgets.QLabel(self.centralwidget)
        self.hasilLabel.setGeometry(QtCore.QRect(610, 50, 450, 420))
        self.hasilLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.hasilLabel.setText("")
        self.hasilLabel.setObjectName("hasilLabel")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(800, 480, 75, 23))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOperasi_Titik = QtWidgets.QMenu(self.menubar)
        self.menuOperasi_Titik.setObjectName("menuOperasi_Titik")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGrayScale = QtWidgets.QAction(MainWindow)
        self.actionGrayScale.setObjectName("actionGrayScale")
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionSave_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionBrightness = QtWidgets.QAction(MainWindow)
        self.actionBrightness.setObjectName("actionBrightness")
        self.actionSimple_Contrast = QtWidgets.QAction(MainWindow)
        self.actionSimple_Contrast.setObjectName("actionSimple_Contrast")
        self.actionContrast_Stretching = QtWidgets.QAction(MainWindow)
        self.actionContrast_Stretching.setObjectName("actionContrast_Stretching")
        self.actionNegative_Image = QtWidgets.QAction(MainWindow)
        self.actionNegative_Image.setObjectName("actionNegative_Image")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuOperasi_Titik.addAction(self.actionGrayScale)
        self.menuOperasi_Titik.addAction(self.actionBrightness)
        self.menuOperasi_Titik.addAction(self.actionSimple_Contrast)
        self.menuOperasi_Titik.addAction(self.actionContrast_Stretching)
        self.menuOperasi_Titik.addAction(self.actionNegative_Image)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOperasi_Titik.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "Load Image"))
        self.saveButton.setText(_translate("MainWindow", "Save Image"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOperasi_Titik.setTitle(_translate("MainWindow", "Operasi Titik"))
        self.actionGrayScale.setText(_translate("MainWindow", "GrayScale"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionSave_Image.setText(_translate("MainWindow", "Save Image"))
        self.actionBrightness.setText(_translate("MainWindow", "Brightness"))
        self.actionSimple_Contrast.setText(_translate("MainWindow", "Simple Contrast"))
        self.actionContrast_Stretching.setText(_translate("MainWindow", "Contrast Stretching"))
        self.actionNegative_Image.setText(_translate("MainWindow", "Negative Image"))
