# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'D5.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_My_Program_152024141(object):
    def setupUi(self, My_Program_152024141):
        if not My_Program_152024141.objectName():
            My_Program_152024141.setObjectName(u"My_Program_152024141")
        My_Program_152024141.resize(1111, 1022)
        self.actionGrayScale = QAction(My_Program_152024141)
        self.actionGrayScale.setObjectName(u"actionGrayScale")
        self.actionLoad_Image = QAction(My_Program_152024141)
        self.actionLoad_Image.setObjectName(u"actionLoad_Image")
        self.actionSave_Image = QAction(My_Program_152024141)
        self.actionSave_Image.setObjectName(u"actionSave_Image")
        self.actionBrightness = QAction(My_Program_152024141)
        self.actionBrightness.setObjectName(u"actionBrightness")
        self.actionSimple_Contrast = QAction(My_Program_152024141)
        self.actionSimple_Contrast.setObjectName(u"actionSimple_Contrast")
        self.actionContrast_Stretching = QAction(My_Program_152024141)
        self.actionContrast_Stretching.setObjectName(u"actionContrast_Stretching")
        self.actionNegative_Image = QAction(My_Program_152024141)
        self.actionNegative_Image.setObjectName(u"actionNegative_Image")
        self.actionBiner_Image = QAction(My_Program_152024141)
        self.actionBiner_Image.setObjectName(u"actionBiner_Image")
        self.actionGray_Histogram = QAction(My_Program_152024141)
        self.actionGray_Histogram.setObjectName(u"actionGray_Histogram")
        self.actionRGB_Histogram = QAction(My_Program_152024141)
        self.actionRGB_Histogram.setObjectName(u"actionRGB_Histogram")
        self.actionHistogram_Equalization = QAction(My_Program_152024141)
        self.actionHistogram_Equalization.setObjectName(u"actionHistogram_Equalization")
        self.actionTranslasi = QAction(My_Program_152024141)
        self.actionTranslasi.setObjectName(u"actionTranslasi")
        self.actionRotasi = QAction(My_Program_152024141)
        self.actionRotasi.setObjectName(u"actionRotasi")
        self.actionResize = QAction(My_Program_152024141)
        self.actionResize.setObjectName(u"actionResize")
        self.actionCrop = QAction(My_Program_152024141)
        self.actionCrop.setObjectName(u"actionCrop")
        self.actionTambah = QAction(My_Program_152024141)
        self.actionTambah.setObjectName(u"actionTambah")
        self.actionKurang = QAction(My_Program_152024141)
        self.actionKurang.setObjectName(u"actionKurang")
        self.actionKali = QAction(My_Program_152024141)
        self.actionKali.setObjectName(u"actionKali")
        self.actionBagi = QAction(My_Program_152024141)
        self.actionBagi.setObjectName(u"actionBagi")
        self.actionAnd = QAction(My_Program_152024141)
        self.actionAnd.setObjectName(u"actionAnd")
        self.actionOr = QAction(My_Program_152024141)
        self.actionOr.setObjectName(u"actionOr")
        self.actionXor = QAction(My_Program_152024141)
        self.actionXor.setObjectName(u"actionXor")
        self.actionFilter = QAction(My_Program_152024141)
        self.actionFilter.setObjectName(u"actionFilter")
        self.actionMean_Filter = QAction(My_Program_152024141)
        self.actionMean_Filter.setObjectName(u"actionMean_Filter")
        self.actionGaussian_Filter = QAction(My_Program_152024141)
        self.actionGaussian_Filter.setObjectName(u"actionGaussian_Filter")
        self.actionSharpening = QAction(My_Program_152024141)
        self.actionSharpening.setObjectName(u"actionSharpening")
        self.actionMedian_Filter = QAction(My_Program_152024141)
        self.actionMedian_Filter.setObjectName(u"actionMedian_Filter")
        self.centralwidget = QWidget(My_Program_152024141)
        self.centralwidget.setObjectName(u"centralwidget")
        self.loadButton = QPushButton(self.centralwidget)
        self.loadButton.setObjectName(u"loadButton")
        self.loadButton.setGeometry(QRect(240, 480, 75, 23))
        self.imgLabel = QLabel(self.centralwidget)
        self.imgLabel.setObjectName(u"imgLabel")
        self.imgLabel.setGeometry(QRect(60, 50, 450, 420))
        self.imgLabel.setFrameShape(QFrame.Box)
        self.hasilLabel = QLabel(self.centralwidget)
        self.hasilLabel.setObjectName(u"hasilLabel")
        self.hasilLabel.setGeometry(QRect(610, 50, 450, 420))
        self.hasilLabel.setFrameShape(QFrame.Box)
        self.saveButton = QPushButton(self.centralwidget)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(800, 480, 75, 23))
        self.before = QLabel(self.centralwidget)
        self.before.setObjectName(u"before")
        self.before.setGeometry(QRect(260, 30, 47, 13))
        self.after = QLabel(self.centralwidget)
        self.after.setObjectName(u"after")
        self.after.setGeometry(QRect(850, 30, 47, 13))
        My_Program_152024141.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(My_Program_152024141)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1111, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOperasi_Titik = QMenu(self.menubar)
        self.menuOperasi_Titik.setObjectName(u"menuOperasi_Titik")
        self.menuHistogram = QMenu(self.menubar)
        self.menuHistogram.setObjectName(u"menuHistogram")
        self.menuGeometri = QMenu(self.menubar)
        self.menuGeometri.setObjectName(u"menuGeometri")
        self.menuOperasi_Aritmatika = QMenu(self.menubar)
        self.menuOperasi_Aritmatika.setObjectName(u"menuOperasi_Aritmatika")
        self.menuOperasi_Boolean = QMenu(self.menubar)
        self.menuOperasi_Boolean.setObjectName(u"menuOperasi_Boolean")
        self.menuOperasi_Spasial = QMenu(self.menubar)
        self.menuOperasi_Spasial.setObjectName(u"menuOperasi_Spasial")
        My_Program_152024141.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(My_Program_152024141)
        self.statusbar.setObjectName(u"statusbar")
        My_Program_152024141.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOperasi_Titik.menuAction())
        self.menubar.addAction(self.menuHistogram.menuAction())
        self.menubar.addAction(self.menuGeometri.menuAction())
        self.menubar.addAction(self.menuOperasi_Aritmatika.menuAction())
        self.menubar.addAction(self.menuOperasi_Boolean.menuAction())
        self.menubar.addAction(self.menuOperasi_Spasial.menuAction())
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuOperasi_Titik.addAction(self.actionGrayScale)
        self.menuOperasi_Titik.addAction(self.actionBrightness)
        self.menuOperasi_Titik.addAction(self.actionSimple_Contrast)
        self.menuOperasi_Titik.addAction(self.actionContrast_Stretching)
        self.menuOperasi_Titik.addAction(self.actionNegative_Image)
        self.menuOperasi_Titik.addAction(self.actionBiner_Image)
        self.menuHistogram.addAction(self.actionGray_Histogram)
        self.menuHistogram.addAction(self.actionRGB_Histogram)
        self.menuHistogram.addAction(self.actionHistogram_Equalization)
        self.menuGeometri.addAction(self.actionTranslasi)
        self.menuGeometri.addAction(self.actionRotasi)
        self.menuGeometri.addAction(self.actionResize)
        self.menuGeometri.addAction(self.actionCrop)
        self.menuOperasi_Aritmatika.addAction(self.actionTambah)
        self.menuOperasi_Aritmatika.addAction(self.actionKurang)
        self.menuOperasi_Aritmatika.addAction(self.actionKali)
        self.menuOperasi_Aritmatika.addAction(self.actionBagi)
        self.menuOperasi_Boolean.addAction(self.actionAnd)
        self.menuOperasi_Boolean.addAction(self.actionOr)
        self.menuOperasi_Boolean.addAction(self.actionXor)
        self.menuOperasi_Spasial.addAction(self.actionFilter)
        self.menuOperasi_Spasial.addAction(self.actionMean_Filter)
        self.menuOperasi_Spasial.addAction(self.actionGaussian_Filter)
        self.menuOperasi_Spasial.addAction(self.actionSharpening)
        self.menuOperasi_Spasial.addAction(self.actionMedian_Filter)

        self.retranslateUi(My_Program_152024141)

        QMetaObject.connectSlotsByName(My_Program_152024141)
    # setupUi

    def retranslateUi(self, My_Program_152024141):
        My_Program_152024141.setWindowTitle(QCoreApplication.translate("My_Program_152024141", u"MainWindow", None))
        self.actionGrayScale.setText(QCoreApplication.translate("My_Program_152024141", u"GrayScale", None))
        self.actionLoad_Image.setText(QCoreApplication.translate("My_Program_152024141", u"Load Image", None))
        self.actionSave_Image.setText(QCoreApplication.translate("My_Program_152024141", u"Save Image", None))
        self.actionBrightness.setText(QCoreApplication.translate("My_Program_152024141", u"Brightness", None))
        self.actionSimple_Contrast.setText(QCoreApplication.translate("My_Program_152024141", u"Simple Contrast", None))
        self.actionContrast_Stretching.setText(QCoreApplication.translate("My_Program_152024141", u"Contrast Stretching", None))
        self.actionNegative_Image.setText(QCoreApplication.translate("My_Program_152024141", u"Negative Image", None))
        self.actionBiner_Image.setText(QCoreApplication.translate("My_Program_152024141", u"Biner Image", None))
        self.actionGray_Histogram.setText(QCoreApplication.translate("My_Program_152024141", u"Histogram Grayscale", None))
        self.actionRGB_Histogram.setText(QCoreApplication.translate("My_Program_152024141", u"Histogram RGB", None))
        self.actionHistogram_Equalization.setText(QCoreApplication.translate("My_Program_152024141", u"Histogram Equalization", None))
        self.actionTranslasi.setText(QCoreApplication.translate("My_Program_152024141", u"Translasi", None))
        self.actionRotasi.setText(QCoreApplication.translate("My_Program_152024141", u"Rotasi", None))
        self.actionResize.setText(QCoreApplication.translate("My_Program_152024141", u"Resize", None))
        self.actionCrop.setText(QCoreApplication.translate("My_Program_152024141", u"Crop Image", None))
        self.actionTambah.setText(QCoreApplication.translate("My_Program_152024141", u"Tambah +", None))
        self.actionKurang.setText(QCoreApplication.translate("My_Program_152024141", u"Kurang -", None))
        self.actionKali.setText(QCoreApplication.translate("My_Program_152024141", u"Kali x", None))
        self.actionBagi.setText(QCoreApplication.translate("My_Program_152024141", u"Bagi /", None))
        self.actionAnd.setText(QCoreApplication.translate("My_Program_152024141", u"AND &&", None))
        self.actionOr.setText(QCoreApplication.translate("My_Program_152024141", u"OR ||", None))
        self.actionXor.setText(QCoreApplication.translate("My_Program_152024141", u"XOR ^", None))
        self.actionFilter.setText(QCoreApplication.translate("My_Program_152024141", u"Filtering", None))
        self.actionMean_Filter.setText(QCoreApplication.translate("My_Program_152024141", u"Mean Filtering", None))
        self.actionGaussian_Filter.setText(QCoreApplication.translate("My_Program_152024141", u"Gaussian Filtering", None))
        self.actionSharpening.setText(QCoreApplication.translate("My_Program_152024141", u"Sharpening", None))
        self.actionMedian_Filter.setText(QCoreApplication.translate("My_Program_152024141", u"Median Filtering", None))
        self.loadButton.setText(QCoreApplication.translate("My_Program_152024141", u"Load Image", None))
        self.imgLabel.setText("")
        self.hasilLabel.setText("")
        self.saveButton.setText(QCoreApplication.translate("My_Program_152024141", u"Save Image", None))
        self.before.setText(QCoreApplication.translate("My_Program_152024141", u"BEFORE", None))
        self.after.setText(QCoreApplication.translate("My_Program_152024141", u"AFTER", None))
        self.menuFile.setTitle(QCoreApplication.translate("My_Program_152024141", u"File", None))
        self.menuOperasi_Titik.setTitle(QCoreApplication.translate("My_Program_152024141", u"Operasi Titik", None))
        self.menuHistogram.setTitle(QCoreApplication.translate("My_Program_152024141", u"Histogram", None))
        self.menuGeometri.setTitle(QCoreApplication.translate("My_Program_152024141", u"Geometri", None))
        self.menuOperasi_Aritmatika.setTitle(QCoreApplication.translate("My_Program_152024141", u"Operasi Aritmatika", None))
        self.menuOperasi_Boolean.setTitle(QCoreApplication.translate("My_Program_152024141", u"Operasi Boolean", None))
        self.menuOperasi_Spasial.setTitle(QCoreApplication.translate("My_Program_152024141", u"Operasi Spasial", None))
    # retranslateUi

